name: Update posts.json and Deploy wwwroot/data & wwwroot/images

on:
  push:
    branches: [ master ]
    paths:
      - 'src/BoneLog.Blazor/wwwroot/data/**'
      - 'src/BoneLog.Blazor/wwwroot/images/**'
      - 'src/BoneLog.Blazor/Automations/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Full Build and Deploy"]
    types:
      - completed

jobs:
  update-and-deploy:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Run generate_index.py
      run: python3 src/BoneLog.Blazor/Automations/generate_index.py

    - name: Copy only data and images to temp folder
      run: |
        mkdir -p deploy-folder/data
        mkdir -p deploy-folder/images
        cp -r src/BoneLog.Blazor/wwwroot/data/* deploy-folder/data/
        cp -r src/BoneLog.Blazor/wwwroot/images/* deploy-folder/images/

    - name: Deploy only data and images
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: deploy-folder
        clean: false
